/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdt.chuong3.dohoa.frames;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdt.chuong3.coffeelogic.CoffeeShop;
import lthdt.chuong3.coffeelogic.Manager;

/**
 *
 * @author vuhuy
 */
public class MyCoffee extends javax.swing.JInternalFrame {
    
    Manager[] managers;
    

    /**
     * Creates new form MyCoffee
     */
    public MyCoffee() throws ParseException {
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        CoffeeShop[] a = new CoffeeShop[]{new CoffeeShop("Kha Coffee", "2 Nguyen Hue"),
                                          new CoffeeShop("While garden", " 4 Nguyen Hue"),
                                          new CoffeeShop("Hoang Truc Vien", "3 Nguyen Hue")};
         managers = new Manager[]{
                                   new Manager(a, 1000, "Le Thi A" , 0, df.parse("12-12-1999")),
                                   new Manager(new CoffeeShop[]{
                                         new CoffeeShop("Hoang Hac",  "10 Nguyen Hue")
                                   },
                                      2000, "Nguyen Van B", 1, df.parse("12-12-2000"))
                               };
        for (int i = 0; i < managers.length; i++){
        cbQuanly.addItem(managers[i].getHoten());
        }
        DefaultTableModel model = (DefaultTableModel) tbCoffeeShop.getModel();
        model.setRowCount(0);
        CoffeeShop[] shops = managers[0].getShops();
        for( int i = 0;i < shops.length; i ++){
        model.insertRow(model.getRowCount(), 
                new Object[]{model.getRowCount() + 1, 
                shops[i].getName(),
                shops[i].getAddress()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbQuanly = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCoffeeShop = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Danh sách các quuán cafe");
        setToolTipText("");

        jLabel1.setText("Họ tên người quản lý");

        cbQuanly.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbQuanlyItemStateChanged(evt);
            }
        });

        tbCoffeeShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên quán", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tbCoffeeShop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(cbQuanly, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbQuanly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbQuanlyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbQuanlyItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbCoffeeShop.getModel();
        model.setRowCount(0);
        int index = cbQuanly.getSelectedIndex();
        CoffeeShop[] shops = managers[index].getShops();
        for( int i = 0;i < shops.length; i ++){
        model.insertRow(model.getRowCount(), 
                new Object[]{model.getRowCount() + 1, 
                shops[i].getName(),
                shops[i].getAddress()});
        }
    }//GEN-LAST:event_cbQuanlyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbQuanly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCoffeeShop;
    // End of variables declaration//GEN-END:variables
}
